name: Mirror GitHub repos to Gitee

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror multiple repos
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/oceanfrost
          dst: gitee/RimSort
          dst_key: ${{ secrets.SSH_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          static_list: |
            RimSort/RimSort
            RimSort/Steam-Workshop-Database
            RimSort/Community-Rules-Database
            emipa606/UseThisInstead
            emipa606/NoVersionWarning
          force_update: true
          clone_style: "ssh"
          lfs: true
          debug: true
