name: Mirror GitHub repos to Gitee

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  mirror-rimsort:
    runs-on: ubuntu-latest
    steps:
      - name: Cache cloned repos
        uses: actions/cache@v4
        with:
          path: hub-mirror-cache-rimsort
          key: ${{ runner.os }}-hub-mirror-rimsort-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-hub-mirror-rimsort-
            
      - name: Mirror RimSort Repos
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/RimSort
          dst: gitee/RimSort
          dst_key: ${{ secrets.SSH_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          static_list: "RimSort,Steam-Workshop-Database,Community-Rules-Database"
          force_update: true
          lfs: true
          debug: true
          cache_path: hub-mirror-cache-rimsort

  mirror-emipa606:
    runs-on: ubuntu-latest
    steps:
      - name: Cache cloned repos
        uses: actions/cache@v4
        with:
          path: hub-mirror-cache-emipa606
          key: ${{ runner.os }}-hub-mirror-emipa606-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-hub-mirror-emipa606-

      - name: Mirror emipa606 Repos
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/emipa606
          dst: gitee/RimSort
          dst_key: ${{ secrets.SSH_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          static_list: "UseThisInstead,NoVersionWarning"
          force_update: true
          lfs: true
          debug: true
          cache_path: hub-mirror-cache-emipa606
